Added annotation to ignore None values in Case Classes
rozza/mongo-scala-driver pull request #37
Opened 2017-04-21 11:56 UTC by rozza

SCALA-300

2017-04-21 11:56 UTC, rozza commented
Needs documentation but wanted feedback on the approach first.

2017-04-21 12:10 UTC, JonathanMey3r commented
I really do like the annotation approach. 
This is just what i thought about.

Maybe it should also toggle the "support missing optional values"?
So that without annotation you write and read null values and with annotation you do not?

2017-04-21 12:35 UTC, JonathanMey3r commented
Okay, i just spoke to a colleague and he said: 
"having an annotation from mongo-scala-driver at our domain classes is not so good"

Maybe we can find a better place configure the "IgnoreNull"?

2017-04-21 12:51 UTC, jyemin requested changes

2017-04-21 12:51 UTC, jyemin commented on bson/src/test/scala/org/mongodb/scala/bson/codecs/MacrosSpec.scala
> +    roundTrip(OptionalValueIgnoreNone("Bob", None), """{name: "Bob"}""", classOf[OptionalValueIgnoreNone])
Though Option<T> is preferred to null in Scala, the behavior of actual null values should be defined.  Currently both of these tests result in an NPE:

    roundTrip(OptionalValueIgnoreNone("Bob", null), """{"name": "Bob", value: null}""", classOf[OptionalValueIgnoreNone]);
    roundTrip(OptionalValueIgnoreNone(null, None), """{"name": null}""", classOf[OptionalValueIgnoreNone]);

2017-04-21 12:51 UTC, jyemin commented on bson/src/main/scala/org/mongodb/scala/bson/codecs/Macros.scala
> +    case class IgnoreNone() extends StaticAnnotation
I'm able to add this annotation to an individual field, e.g.

    case class OptionalValueIgnoreNone(name: String,
                                       @IgnoreNone 
                                       value: Option[String])
 
As that currently has no effect, is there a way to make it a compiler error?

2017-04-21 13:16 UTC, rozza commented on bson/src/test/scala/org/mongodb/scala/bson/codecs/MacrosSpec.scala
> +    roundTrip(OptionalValueIgnoreNone("Bob", None), """{name: "Bob"}""", classOf[OptionalValueIgnoreNone])
`OptionalValueIgnoreNone("Bob", null)` should be left as is, it is pure scala and a user error to try and create that case class instance.

2017-04-21 13:20 UTC, rozza commented on bson/src/main/scala/org/mongodb/scala/bson/codecs/Macros.scala
> +    case class IgnoreNone() extends StaticAnnotation
Well that is a valid case class. 

We could make the macro fail in this instance but I'm not sure of the need to check annotations at the field level, with this commit.

2017-04-21 13:36 UTC, jyemin commented on bson/src/test/scala/org/mongodb/scala/bson/codecs/MacrosSpec.scala
> +    roundTrip(OptionalValueIgnoreNone("Bob", None), """{name: "Bob"}""", classOf[OptionalValueIgnoreNone])
What about the second one?

2017-04-21 13:38 UTC, jyemin commented on bson/src/main/scala/org/mongodb/scala/bson/codecs/Macros.scala
> +    case class IgnoreNone() extends StaticAnnotation
So nothing like java.lang.annotation.Target for Scala annotations?

2017-04-21 14:10 UTC, rozza commented on bson/src/main/scala/org/mongodb/scala/bson/codecs/Macros.scala
> +    case class IgnoreNone() extends StaticAnnotation
Just checking now, I'm new to Scala annotations.

2017-04-21 14:27 UTC, rozza commented on bson/src/test/scala/org/mongodb/scala/bson/codecs/MacrosSpec.scala
> +    roundTrip(OptionalValueIgnoreNone("Bob", None), """{name: "Bob"}""", classOf[OptionalValueIgnoreNone])
Same its heresy in Scala, but added SCALA-301 to convert to a `CodecConfigurationException`

2017-04-21 14:28 UTC, rozza commented on bson/src/main/scala/org/mongodb/scala/bson/codecs/Macros.scala
> +    case class IgnoreNone() extends StaticAnnotation
No such thing in the Scala world.

2017-04-21 14:34 UTC, jyemin commented on bson/src/test/scala/org/mongodb/scala/bson/codecs/MacrosSpec.scala
> +    roundTrip(OptionalValueIgnoreNone("Bob", None), """{name: "Bob"}""", classOf[OptionalValueIgnoreNone])
Acknowledged

2017-04-21 14:34 UTC, jyemin commented on bson/src/main/scala/org/mongodb/scala/bson/codecs/Macros.scala
> +    case class IgnoreNone() extends StaticAnnotation
Acknowledged.

2017-04-25 09:12 UTC, rozza commented
I rebased and this now sits on top of #38 

The changes can be seen in 063e73a. 

The upshot is you no longer need to annotate your case class to ignore None values.
Currently, I don't have any plans to add anymore annotations so we could remove it for now.

2017-04-28 10:58 UTC, rozza commented
Ok final updates - removed the annotation, inclusion of None values is solely based on how the Codec is created.

2017-05-02 19:59 UTC, jyemin approved these changes

2017-05-04 09:11 UTC, closed without merging

2017-05-04 09:11 UTC, rozza commented
Rebased and merged